spring:
  flyway:
    enabled: 'true'
    locations: classpath:db/migration
  datasource:
    username: ${DATABASE_USERNAME}
    url: ${DATABASE_URL}
    password: ${DATABASE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: OngPatinhas
  jpa:
    hibernate:
      ddl-auto: validate
  mercadopago:
    access-token: ${MP_ACCESS_TOKEN}
    public-key: ${MP_PUBLIC_KEY}
    success:
      url: https://portfolio-azure-nine-95.vercel.app/success
    pending:
      url: https://portfolio-azure-nine-95.vercel.app/pending
    failure:
      url: https://portfolio-azure-nine-95.vercel.app/failure
  captcha:
    secret-key: ${RC_SECRET_KEY}