spring:
  flyway:
    enabled: 'true'
    locations: classpath:db/migration
  datasource:
    username: ${DATABASE_USERNAME}
    url: ${DATABASE_URL}
    password: ${DATABASE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: OngPatinhas
  logging:
    file:
      path: /var/log/springboot/spring.log
  jpa:
    hibernate:
      ddl-auto: validate
  mercadopago:
    access-token: ${MP_ACCESS_TOKEN}
    public-key: ${MP_PUBLIC_KEY}
    success:
      url: https://ong-patinhas.ddns.net/sucesso
    pending:
      url: https://ong-patinhas.ddns.net/pendente
    failure:
      url: https://ong-patinhas.ddns.net/cancelado
  captcha:
    secret-key: ${RC_SECRET_KEY}
