name: Build and Dockerize Spring App

on:
  push:
    branches: [*]
  pull_request:
    branches: [*]
#teste
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Run tests with Maven
        run: mvn test

      - name: Build with Maven
        run: mvn clean package

      - name: Build Docker image
        run: docker build -t ong-patinhas-app .

      - name: Push Docker image
        run: |
          echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker tag ong-patinhas-app:latest ${{ secrets.DOCKER_USERNAME }}/ong-patinhas-app:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/ong-patinhas-app:latest



