name: Build and Push Docker Image

on:
  push:
    branches: [*] # ou a branch de deploy
  workflow_run:
    workflows: ["Build and Test Spring App"]
    types:
      - completed

jobs:
  dockerize:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t ong-patinhas-app .

      - name: Push Docker image
        run: |
          echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker tag ong-patinhas-app:latest ${{ secrets.DOCKER_USERNAME }}/ong-patinhas-app:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/ong-patinhas-app:latest