INSERT INTO ongpatinhas.tb_dogs (id, name, breed, age, skills, image) VALUES
(UUID(), 'Rex', 'Labrador', '2 anos', 'Amigável com crianças, adora brincar de bola e é muito obediente', 'cachorro1.jpeg'),
(UUID(), 'Bella', 'Lulu da Pomerânia', '1 ano', 'Companheira e carinhosa, late quando estranhos se aproximam', 'cachorro2.jpeg'),
(UUID(), 'Max', 'Cavalier', '3 anos', 'Calmo, gosta de colo e se adapta bem em apartamentos', 'cachorro3.jpeg'),
(UUID(), 'Luna', 'Lulu da Pomerânia', '4 anos', 'Muito ativa, gosta de passeios longos e aprende truques rapidamente', 'cachorro4.jpeg'),
(UUID(), 'Thor', 'Dogue de Bordeaux', '6 anos', 'Protetor da família, dócil com crianças e ótimo cão de guarda', 'cachorro5.jpeg'),
(UUID(), 'Freed', 'Golden Retriever', '2 anos', 'Ama água, brincadeiras ao ar livre e é fácil de treinar', 'cachorro6.jpeg'),
(UUID(), 'Amadeu', 'Rottweiler', '2 anos', 'Leal, inteligente, ótimo para guarda mas também muito afetuoso com a família', 'cachorro7.jpeg'),
(UUID(), 'Toto', 'Vira-lata', '4 meses', 'Filhote brincalhão, cheio de energia e curioso com tudo', 'cachorro8.jpeg'),
(UUID(), 'Red', 'Shih-Tzu', '1 mês', 'Muito dócil, adora carinho e se dá bem com outros pets', 'cachorro9.jpeg'),
(UUID(), 'Pit', 'Bichon Frisé', '1 ano', 'Alegre, adora correr e brincar com crianças pequenas', 'cachorro10.jpeg'),
(UUID(), 'Donatelo', 'Bernese MaltDog', '5 anos', 'Sociável, gosta de companhia, se adapta bem em ambientes maiores', 'cachorro11.jpeg'),
(UUID(), 'Vegeta', 'Yorkshire', '8 meses', 'Pequeno mas cheio de energia, gosta de explorar e correr', 'cachorro12.jpeg'),
(UUID(), 'Kakaroto', 'Lulu da Pomerânia', '8 meses', 'Brincalhão, gosta de aprender truques e receber atenção', 'cachorro13.jpeg'),
(UUID(), 'Buma', 'Maltês', '8 meses', 'Muito dócil, adora colo e é um ótimo cão de companhia', 'cachorro14.jpeg'),
(UUID(), 'Tony', 'Border Collie', '1 ano', 'Extremamente inteligente, aprende comandos com facilidade e adora desafios', 'cachorro15.jpeg'),
(UUID(), 'Kali', 'Vira-lata', '1 ano', 'Independente, mas muito carinhosa, se adapta bem em qualquer lar', 'cachorro16.jpeg'),
(UUID(), 'Dolar', 'Lulu da Pomerânia', '1 ano', 'Esperto, adora brincar e é bastante apegado ao tutor', 'cachorro17.jpeg'),
(UUID(), 'Jorge', 'Chihuahua', '1 ano', 'Valente, gosta de ser o centro das atenções e é fiel ao dono', 'cachorro18.jpeg');