#name: Build and Test Spring App
#
#on:
#  push:
#    branches: ["**"]
#  pull_request:
#    branches: ["**"]
#
#jobs:
#  build:
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: Checkout do código
#        uses: actions/checkout@v3
#
#      - name: Set up JDK 21
#        uses: actions/setup-java@v4
#        with:
#          distribution: 'temurin'
#          java-version: '21'
#
#      - name: Run tests with Maven
#        run: mvn test
#
#      - name: Build with Maven
#        run: mvn clean package


name: Build, Test and Dockerize Spring App with Maven

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout del código
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Configura Java
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Run tests with Maven
        run: mvn --batch-mode --update-snapshots test,


      - name: Build with Maven
        run: mvn --batch-mode clean package
#      # 3. Roda los tests de Maven
#      - name: Run tests with Maven
#        run: mvn test
#
#      # 4. Build del proyecto (genera el jar)
#      - name: Build with Maven
#        run: mvn clean package

#      # 5. Construye la imagen Docker (usa el jar generado por Maven)
#      - name: Build Docker image
#        run: docker build -t ong-patinhas-app .
#
#      # 6. Login a Docker Hub
#      - name: Login to Docker Hub
#        run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
#
#      # 7. Tag y push de la imagen a Docker Hub
#      - name: Tag and Push Docker image
#        run: |
#          docker tag ong-patinhas-app:latest ${{ secrets.DOCKER_USERNAME }}/ong-patinhas-app:latest
#          docker push ${{ secrets.DOCKER_USERNAME }}/ong-patinhas-app:latest